import Head from 'next/head';
import React from 'react';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import useSSR from 'use-ssr';
import axios from 'axios';

function GetDate() {
  var today = new Date();
  var dd = String(today.getDate()).padStart(2, '0');
  var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
  var yyyy = today.getFullYear();

  today = yyyy + '-' + mm + '-' + dd;
  console.log(today);
  return today;
}

export default function Home() {
  var { isBrowser, isServer } = useSSR();
  const [DateDepart, setDateDepart] = React.useState('2021-06-19');
  const [DateAuj, setDateAuj] = React.useState(GetDate());
  const [WeightDepart, setWeightDepart] = React.useState(
    WeightAtDay(DateDepart)
  );
  const [email, setEmail] = React.useState('');
  const [email2, setEmail2] = React.useState('');

  React.useEffect(() => {
    const fetchUserEmail = async () => {
      const response = await WeightAtDay('2021-06-19');
      setEmail(response);
    };
    const fetchUserEmail2 = async () => {
      const response = await WeightAtDay(GetDate());
      setEmail2(response);
    };
    fetchUserEmail();
    fetchUserEmail2();
  }, []);

  async function WeightAtDay(date) {
    var url = window.location.href;
    //api.fitbit.com/1/user/[user-id]/body/log/fat/date/[date].json
    var access_token = url.split('#')[1].split('=')[1].split('&')[0];
    var userId = url.split('#')[1].split('=')[2].split('&')[0];
    const api =
      'https://api.fitbit.com/1/user/' +
      userId +
      '/body/log/weight/date/' +
      date +
      '.json';
    const Test = await axios
      .get(api, {
        headers: { Authorization: `Bearer ${access_token}` },
      })
      .then((res) => {
        return res.data.weight[0].weight;
      });
    return Test;
  }
  if (!email) {
    return null;
  }
  console.log(email2);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Quentin's Body <a href='https://nextjs.org'>Dashboard</a>
        </h1>

        <h2>Date & poids de départ</h2>
        <h3>
          {DateDepart} {'   ==>   '}
          {email}
        </h3>
        <h2>Date & poids du jour</h2>
        <h3>
          {DateAuj}
          {'   ==>   '}
          {email2}
        </h3>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
